---
- name: Install Nginx
  yum:
    name: nginx
    update_cache: yes
    state: latest

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ remote_web_user }}"
    group: "{{ remote_web_user }}"
    mode: '0755'

- name: Clean up Nginx default Configuration
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: restart nginx

- name: Set up Nginx VirtualHost
  template:
    src: "host.conf.j2"
    dest: "/etc/nginx/conf.d/{{ http_conf }}"
  notify: restart nginx

- name: Enable VirtualHost
  file:
    dest: "/etc/nginx/sites-enabled"
    src: "/etc/nginx/conf.d/{{ http_conf }}"
    state: "link"
  notify: restart nginx

- name: Schedule nginx process monitor script
  cron:
    name: "check nginx process"
    job: "/tmp/watch.sh"
