#########################################################
# Wordpress on CentOS8 LEMP
#########################################################

---
- hosts: all
  roles:
    -
     role: common
     tags: [system]

- hosts: web
  roles:
    -
     role: php
     tags: [php]
    -
     role: nginx
     tags: [nginx]
    -
     role: ssl
     tags: [ssl]
    -
     role: mariadb
     tags: [mariadb]
    -
     role: wordpress
     tags: [wordpress]
