#########################################################
# Wordpress on CentOS8 LEMP
#########################################################

---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  roles:
    -
     role: common
     tags: [system]

- hosts: default
  vars_files:
    - vars/default.yml
  remote_user: "{{ remote_sudo_user }}"
  become: true

  roles:
    -
     role: php
     tags: [php]
    -
     role: nginx
     tags: [nginx]
    -
     role: ssl
     tags: [ssl]
    -
     role: mysql
     tags: [mysql]
    -
     role: wordpress
     tags: [wordpress]
