---
# this is the sudo user that should already be setup on the server.  Any sudo roles will use this user and this is the
# user ansible initially connects as.
remote_sudo_user: root

#System Settings
system_modules: [ 'python3', 'wget', 'vim', 'epel-release' ]
php_modules: [ 'MySQL-python', 'php', 'php-pdo', 'php-mysqlnd', 'php-fpm' ]
lemp_modules: [ 'nginx', 'mariadb-server', 'MySQL-python', 'php', 'php-pdo', 'php-mysqlnd', 'php-fpm']

#MySQL Settings
mysql_root_password: "root"
mysql_db: "wordpress"
mysql_user: "wp_user"
mysql_password: "wp_user"

#HTTP Settings
remote_web_user: "nginx"
http_host: "www.example.com"
http_conf: "www.example.com.conf"
http_port: "80"
