---
- name: Install MariaDB modules
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop: "{{ mysql_modules }}"

- name: Ensure mariadb is started
  service:
    name: mariadb
    state: started
    enabled: true
  tags: [ mariadb, mariadb-root ]

- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
  tags: mariadb

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    host: localhost
    login_user: root
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"
  when: root_pwd_check.rc == 0
  tags: [ mariadb, mariadb-root ]

- name: Create database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mariadb ]

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mariadb ]
